In [9]:
import numpy as np

In [2]:
lst=[1,2,3]

In [3]:
arr=np.array(lst)

In [4]:
type(lst)

list

In [5]:
type(arr)

numpy.ndarray

In [6]:
lst.append(4)

In [7]:
lst

[1, 2, 3, 4]

In [8]:
arr.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
arr+np.array([4])

In [ ]:
arr+np.array([4,5,6])

In [ ]:
arr+np.array([4,5])

In [ ]:
2*arr

In [ ]:
2*lst

In [ ]:
lst+lst

In [ ]:
lst2=[]
for e in lst:
    lst2.append(e+3)

In [ ]:
lst2=[3+e for e in lst]

In [ ]:
lst2

In [ ]:
lst3=[2**e for e in lst]

In [ ]:
lst3

In [ ]:
arr2=arr**2
arr2

In [ ]:
np.sqrt(arr2)

In [ ]:
np.log(arr2)

In [ ]:
np.exp(arr2)

In [ ]:
np.tanh(arr2)

In [ ]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
my_mat

In [ ]:
np.array(my_mat)

In [ ]:
np.arange(0,11,2)

In [ ]:
# fills with zeros in 2d matrix
np.zeros((3,5))

In [ ]:
# fills with ones in 2d matrix
np.ones((4,5,))

In [ ]:
# Return evenly spaced numbers over a specified interval.

# Returns `num` evenly spaced samples, calculated over the
# interval [`start`, `stop`].

np.linspace(0,10,5)

In [ ]:
#Identity matrix
np.eye(4) 

In [ ]:
# Create an array of the given shape and populate it with
# random samples from a uniform distribution
# over ``[0, 1)``.

np.random.rand(5)

In [ ]:
np.random.rand(5,5)

In [ ]:
# Return a sample (or samples) from the "standard normal" distribution.

np.random.randn(5)

In [ ]:
np.random.randn(5,5)

In [ ]:
np.random.randint(1,100)

In [ ]:
# randint(low, high=None, size=None, dtype=int)

# Return random integers from `low` (inclusive) to `high` (exclusive).

np.random.randint(1,100, 10)


In [ ]:
arr2=np.arange(25)
arr2

In [ ]:
ranarr=np.random.randint(0,50,10)

In [ ]:
ranarr

In [ ]:
# Returns an array containing the same data with a new shape.

arr2=arr2.reshape(5,5)
arr2

In [ ]:
# Return the maximum along a given axis.
arr2.max()

In [ ]:
arr2.max(0)

In [ ]:
arr2.max(1)

In [ ]:
# Return the minimum along a given axis.
arr2.min()

In [ ]:
arr2.min()

In [ ]:
arr2.min(0)

In [ ]:
arr2.min(1)

In [ ]:
arr

In [ ]:
arr.max(1)

In [ ]:
# Return indices of the maximum values along the given axis.
arr.argmax()

In [ ]:
arr.argmin()

In [ ]:
arr.shape

In [ ]:
arr2.shape

# Numpay indexing and selection

In [ ]:
arr=np.arange(0,11)

In [ ]:
arr

In [ ]:
arr[8]

In [ ]:
arr[1:4]

In [ ]:
arr[0:5]

In [ ]:
arr[:6]

In [ ]:
arr[1:]

In [ ]:
arr[:]

In [ ]:
arr[:-2]

In [ ]:
arr[-1:]

In [ ]:
arr[0:5]=100
arr

In [ ]:
arr=np.arange(0,11)

In [ ]:
arr1=arr[:]

In [ ]:
arr1

In [ ]:
arr

In [ ]:
arr1[0:5]=100

In [ ]:
arr1

In [ ]:
arr

In [ ]:
arr3=arr.copy()

In [ ]:
arr3[0:3]=99

In [ ]:
arr3

In [ ]:
arr1

In [ ]:
arr

In [ ]:
arr2d=np.array([[1,2,3],[3,4,5],[6,7,8]])

In [ ]:
arr2d

In [ ]:
arr2d[0][1]

In [ ]:
arr2d[0,1]

In [ ]:
arr2d[1]

In [ ]:
arr2d[:2,1:]

In [ ]:
arr2d[:2]

In [ ]:
arr2d[1:]

In [ ]:
arr=np.arange(1,11)

In [ ]:
arr

In [ ]:
arr>5

In [ ]:
bool_arr=arr>5

In [ ]:
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr>5]

In [ ]:
arr[arr<5]

In [ ]:
arr2d=np.arange(50).reshape(5,10)
arr2d

In [ ]:
arr2d[1:3,4:6]

# Numpy with operations
    1. array with array 
    2. array with scaler
    3. universal array function
    

In [ ]:
arr=np.arange(0,10)

In [ ]:
arr

In [ ]:
arr+arr

In [ ]:
arr-arr

In [ ]:
arr*arr

In [ ]:
arr/2

In [ ]:
arr-100

In [ ]:
arr*70

In [ ]:
1/arr

In [ ]:
arr**3

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
np.max(arr)

In [ ]:
np.min(arr)

In [ ]:
np.sin(arr)

In [ ]:
np.cos(arr)

# Dot product


The dot product of two vectors **A** and **B**, denoted as **A · B**, is defined as:

$$
\mathbf{A} \cdot \mathbf{B} = \sum_{i=1}^n A_i B_i = A_1B_1 + A_2B_2 + \cdots + A_nB_n
$$


The dot product of two vectors **a** and **b** can also be represented as:

$$
a \cdot b = a^T b = \sum_{d=1}^D a_d b_d
$$

Where:
- \(a^T\) is the transpose of vector **a** (a row vector).
- \(b\) is the column vector.
- \(a_d\) and \(b_d\) are the \(d\)-th components of vectors **a** and **b**, respectively.
- \(D\) is the dimension of the vectors.


### Key Points:
- \(a^T b\): The dot product can also be viewed as a **matrix multiplication** between a row vector \(a^T\) and a column vector \(b\).
- The summation form $$ (\sum_{d=1}^D a_d b_d) $$ explicitly computes the dot product by summing the products of corresponding elements.

This notation is very common in machine learning and linear algebra. It bridges the gap between **vector operations** and **matrix operations**. 😊

In [ ]:
a=np.array([1,2])
b=np.array([3,4])

In [ ]:
dot=0
for e, f in zip(a,b):
    dot+=e*f
dot

In [ ]:
dot=0
for i in range(len(a)):
    dot+=a[i]*b[i]
dot

In [ ]:
a*b

In [ ]:
np.sum(a*b)

In [ ]:
(a*b).sum()

In [ ]:
np.dot(a,b)

In [ ]:
a.dot(b)

In [ ]:
a@b

The dot product of two vectors **A** and **B** can also be defined as:

$$
\mathbf{A} \cdot \mathbf{B} = \|\mathbf{A}\| \|\mathbf{B}\| \cos(\theta)
$$


The dot product can also be represented using the relationship between magnitudes and the cosine of the angle between two vectors:

$$
a^T b = \|a\| \|b\| \cos \theta_{ab}
$$

Where:
- $$ (\cos \theta_{ab}) $$ is the cosine of the angle between vectors \(a\) and \(b\).
- The cosine of the angle can be computed as:

$$
\cos \theta_{ab} = \frac{a^T b}{\|a\| \|b\|}
$$

The magnitude of a vector \(a\) is defined as:

$$
\|a\| = \sqrt{\sum_{d=1}^D a_d^2}
$$

Where:
- $$ \(a_d) $$ is the \(d\)-th component of vector \(a\).
- \(D\) is the dimension of the vector.


In [ ]:
amag=np.sqrt((a*a).sum())
amag

In [ ]:
np.linalg.norm(a)

In [ ]:
cosangle=a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
cosangle

In [ ]:
angle=np.arccos(cosangle)
angle

# Matrix

In [ ]:
lst_a=[[1,2],[3,4]]
mat_a=np.array(lst_a)
mat_a

In [ ]:
mat_a.T

In [ ]:
np.exp(lst_a)

In [ ]:
np.exp(mat_a)

In [ ]:
lst_b=[[1,2,3],[4,5,6]]
mat_b=np.array(lst_b)
mat_b

In [ ]:
mat_a.dot(mat_b)

In [ ]:
mat_a.dot(mat_b.T)

In [ ]:
# Compute the determinant of an array.
np.linalg.det(mat_a)


In [ ]:
np.linalg.inv(mat_a)

In [ ]:
# We will get identity matrix
np.linalg.inv(mat_a).dot(mat_a)

In [ ]:
# Return the sum along diagonals of the array.
np.trace(mat_a)

In [ ]:
np.diag(mat_a)

In [ ]:
np.diag([1,4])

In [ ]:
# Compute the eigenvalues and right eigenvectors of a square array.
np.linalg.eig(mat_a)

In [ ]:
Lam, V=np.linalg.eig(mat_a)

In [ ]:
V[:, 0] * Lam[0] == mat_a @ V[:,0]

In [ ]:
V[:, 0] * Lam[0], mat_a @ V[:,0]

In [ ]:
# Returns True if two arrays are element-wise equal within a tolerance.
np.allclose(V[:, 0] * Lam[0], mat_a @ V[:,0])

In [ ]:
np.allclose(V @ np.diag(Lam), mat_a @ V)

# Solving Linear System

### Linear Systems: Example Problem

The admission fee at a small fair is `$1.50` for children and `$4.00` for adults. On a certain day, 2200 people enter the fair, and $5050 is collected. How many children and how many adults attended?

This problem can be represented as a system of linear equations:

1. Total number of people:
   $$
   x_1 + x_2 = 2200
   $$

2. Total money collected:
   $$
   1.5x_1 + 4x_2 = 5050
   $$

Where:
- \(x_1\) is the number of children.
- \(x_2\) is the number of adults.

We have **2 equations and 2 unknowns** to solve.


### Linear System in Matrix Form

The system of equations can be written in matrix form as:

$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}, \quad
A = \begin{pmatrix} 1 & 1 \\ 1.5 & 4 \end{pmatrix}, \quad
b = \begin{pmatrix} 2200 \\ 5050 \end{pmatrix}
$$

The system of equations becomes:

$$
Ax = b \quad \iff \quad x = A^{-1}b
$$


### Don't do that literally!

- The **"inverse"** is slower and less accurate.
- There are better algorithms to **solve** linear systems.

```python
# Correct way to solve a linear system
x = np.linalg.solve(A, b)  # yes

# Incorrect and inefficient way
x = np.linalg.inv(A).dot(b)  # no


In [10]:
A=np.array([[1,1],[1.5,4]])
b=np.array([2200,5050])

In [11]:
x=np.linalg.solve(A,b)

In [12]:
x

array([1500.,  700.])

In [13]:
x = np.linalg.inv(A).dot(b)
x

array([1500.,  700.])

# Genrating Data

In [14]:
R=np.random.randn(10000)

In [15]:
R.mean()

np.float64(-0.011238369579992453)

In [16]:
np.mean(R)

np.float64(-0.011238369579992453)

In [17]:
R.var()

np.float64(0.9979892337805853)

In [18]:
R=np.random.randn(10000, 3)

In [20]:
R.mean(axis=1)

array([ 0.36305266, -0.50281045,  1.17861318, ..., -0.64470507,
        0.49387034,  0.23912559], shape=(10000,))

In [22]:
np.cov(R).shape

(10000, 10000)

In [27]:
np.cov(R.T)

array([[ 1.01558747e+00, -8.94566849e-03, -8.68612545e-03],
       [-8.94566849e-03,  1.01572606e+00, -4.93703996e-06],
       [-8.68612545e-03, -4.93703996e-06,  9.87697227e-01]])

In [26]:
np.cov(R, rowvar=False)

array([[ 1.01558747e+00, -8.94566849e-03, -8.68612545e-03],
       [-8.94566849e-03,  1.01572606e+00, -4.93703996e-06],
       [-8.68612545e-03, -4.93703996e-06,  9.87697227e-01]])

In [30]:
np.random.randint(0,10,size=(3,3))

array([[3, 0, 7],
       [7, 4, 0],
       [4, 2, 0]])

In [32]:
np.random.choice(10, size=(3,3))

array([[4, 1, 3],
       [8, 2, 4],
       [0, 6, 4]])