In [236]:
import numpy as np
import pandas as pd
A=np.arange(0,10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
A[A%2]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [238]:
df.values

array([[8, 5, 9, 8],
       [7, 5, 3, 8],
       [8, 8, 1, 5],
       [2, 9, 4, 2],
       [9, 5, 4, 3]])

In [239]:
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':10,'b':20,'c':30}

In [240]:
pd.Series(data=my_data)

0    10
1    20
2    30
dtype: int64

In [241]:
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [242]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [243]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [244]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [245]:
pd.Series(data=[sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [246]:
ser1=pd.Series([1,2,3,4], ['USA', 'Germany', 'USSR', 'Japan'])

In [247]:
ser2=pd.Series([1,2,5,4], ['USA', 'Germany', 'UAE', 'Japan'])

In [248]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [249]:
ser2

USA        1
Germany    2
UAE        5
Japan      4
dtype: int64

In [250]:
ser1['USA']

np.int64(1)

In [251]:
ser2['UAE']

np.int64(5)

In [252]:
ser3=pd.Series(data=labels)

In [253]:
ser3

0    a
1    b
2    c
dtype: object

In [254]:
ser3[0]

'a'

In [255]:
ser1+ser2

Germany    4.0
Japan      8.0
UAE        NaN
USA        2.0
USSR       NaN
dtype: float64

In [256]:
np.random.seed(101)

In [257]:
df=pd.DataFrame(np.random.randn(5,4), ['A','B','C','D','E'], ['W','X', 'Y', 'Z'])

In [258]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [259]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [260]:
type(df['W'])

pandas.core.series.Series

In [261]:
type(df)

pandas.core.frame.DataFrame

In [262]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [263]:
df['new']=df['W']+df['Y']

In [264]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [265]:
df.drop('new', axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [266]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [267]:
df.drop('new', axis=1, inplace=True)

In [268]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [269]:
df.drop('E', axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [270]:
df=pd.DataFrame(np.random.randint(1,10,size=(5,4)), ['A','B','C','D','E'], ['W','X', 'Y', 'Z'])

In [271]:
df

W  X  Y  Z
A  8  5  9  8
B  7  5  3  8
C  8  8  1  5
D  2  9  4  2
E  9  5  4  3

# Multi Level Indexing 

In [272]:
df = pd.DataFrame(
    np.random.randint(1, 10, size=(5, 4)),  # Generate a 5x4 array of random integers
    index=['A', 'B', 'C', 'D', 'E'],        # Row labels
    columns=['W', 'X', 'Y', 'Z']            # Column labels
)

In [273]:
df

W  X  Y  Z
A  4  4  8  5
B  9  7  4  8
C  7  6  7  3
D  3  2  4  4
E  4  5  6  6

In [274]:
row_sum=df.sum(axis=1)
row_sum

A    21
B    28
C    23
D    13
E    21
dtype: int64

In [275]:
col_sum=df.sum(axis=0)
col_sum

W    27
X    24
Y    29
Z    26
dtype: int64

In [276]:
# Select lables bassed index
df.loc['A']

W    4
X    4
Y    8
Z    5
Name: A, dtype: int64

In [277]:
# Select int bassed index
df.iloc[0]

W    4
X    4
Y    8
Z    5
Name: A, dtype: int64

In [278]:
df.loc['B','Y']

np.int64(4)

In [279]:
df.loc[['A','B'],['W','Y']]

W  Y
A  4  8
B  9  4

In [280]:
booldf=df>3

In [281]:
df[booldf]

W    X  Y    Z
A  4.0  4.0  8  5.0
B  9.0  7.0  4  8.0
C  7.0  6.0  7  NaN
D  NaN  NaN  4  4.0
E  4.0  5.0  6  6.0

In [282]:
df[df['W']>3]

W  X  Y  Z
A  4  4  8  5
B  9  7  4  8
C  7  6  7  3
E  4  5  6  6

In [283]:
df[df['W']>3]['X']

A    4
B    7
C    6
E    5
Name: X, dtype: int64

In [284]:
df[df['W']>3][['X','Y']]

X  Y
A  4  8
B  7  4
C  6  7
E  5  6

In [285]:
df.reset_index(inplace=True)

In [286]:
df

index  W  X  Y  Z
0     A  4  4  8  5
1     B  9  7  4  8
2     C  7  6  7  3
3     D  3  2  4  4
4     E  4  5  6  6

In [287]:
# df.reset_index(inplace=True)

In [288]:
newind='CA NY WY OR CO'.split()

In [289]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [290]:
df['States']=newind

In [291]:
df

index  W  X  Y  Z States
0     A  4  4  8  5     CA
1     B  9  7  4  8     NY
2     C  7  6  7  3     WY
3     D  3  2  4  4     OR
4     E  4  5  6  6     CO

In [292]:
df.set_index('States', inplace=True)

In [293]:
df

index  W  X  Y  Z
States                  
CA         A  4  4  8  5
NY         B  9  7  4  8
WY         C  7  6  7  3
OR         D  3  2  4  4
CO         E  4  5  6  6

In [294]:
#Index lavels
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_tuples=list(zip(outside, inside))


In [295]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [296]:
inside

[1, 2, 3, 1, 2, 3]

In [297]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [298]:
hier_index=pd.MultiIndex.from_tuples(hier_tuples)

In [299]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [300]:
df=pd.DataFrame(
    np.random.randint(1,10,size=(6,2)),
    index=hier_index, 
    columns=['A', 'B']
)

In [301]:
df

A  B
G1 1  9  4
   2  7  9
   3  8  6
G2 1  8  6
   2  5  5
   3  8  4

In [302]:
df.loc['G1']

A  B
1  9  4
2  7  9
3  8  6

In [303]:
df.loc['G1'].loc[1]

A    9
B    4
Name: 1, dtype: int64

In [304]:
df.index.names=['Groups', 'Num']

In [305]:
df

A  B
Groups Num      
G1     1    9  4
       2    7  9
       3    8  6
G2     1    8  6
       2    5  5
       3    8  4

In [306]:
df.loc['G2'].loc[2]['B']

np.int64(5)

In [308]:
df.xs('G1')

A  B
Num      
1    9  4
2    7  9
3    8  6

In [311]:
df.xs(1,level='Num')

A  B
Groups      
G1      9  4
G2      8  6

In [363]:
d={
    'A':[1,2,np.nan],
    'B':[5,np.nan, np.nan],
    'C':[1,2,3]
  }

In [364]:
df=pd.DataFrame(d)

In [365]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [366]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [367]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [368]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [369]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [370]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [371]:
df.fillna(value="Fill Value")

A           B  C
0         1.0         5.0  1
1         2.0  Fill Value  2
2  Fill Value  Fill Value  3

In [372]:
df['A'] = df['A'].fillna(value=df['A'].mean())

In [373]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  1.5  NaN  3

In [376]:
df.fillna({'B': df['B'].median()}, inplace=True)


In [377]:
df

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

In [386]:
data ={
    'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
    'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
    'Sales': [200,120,340,124,243,350]
    }

In [387]:
data

{'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
 'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
 'Sales': [200, 120, 340, 124, 243, 350]}

In [388]:
df=pd.DataFrame(data)

In [389]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [392]:
byCompany=df.groupby('Company')

In [394]:
print(df.dtypes)

Company    object
Person     object
Sales       int64
dtype: object


In [400]:
import pandas as pd

# Sample DataFrame
data = {
    'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
    'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
    'Sales': [200, 120, 340, 124, 243, 350]
}

# Create DataFrame
df = pd.DataFrame(data)

# Group by Company and calculate mean for numeric columns only
byCompany = df.groupby('Company')
result = byCompany[['Sales']].mean()  # Selecting only the 'Sales' column

print(result)


         Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0


In [402]:
byCompany[['Sales']].std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [403]:
byCompany[['Sales']].max()

Sales
Company       
FB         350
GOOG       200
MSFT       340

In [404]:
byCompany[['Sales']].min()

Sales
Company       
FB         243
GOOG       120
MSFT       124

In [405]:
byCompany[['Sales']].describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [406]:
byCompany[['Sales']].describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000